version: '3.9'

x-logging: &logging
  driver: 'json-file'
  options:
    max-size: '20m'
    max-file: '5'


services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    logging: *logging
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:6.7.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./php-conf/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - wordpress:/var/www/html
    logging: *logging
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.27.3-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot:/etc/letsencrypt
    logging: *logging
    networks:
      - app-network
    
  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot:/etc/letsencrypt
      - wordpress:/var/www/html
    logging: *logging
    command: certonly --webroot --webroot-path=/var/www/html --email contacto@revivestore.pt --agree-tos --no-eff-email --force-renewal -d revivestore -d www.revivestore.pt

volumes:
  certbot:
  wordpress:
  dbdata:

networks:
  app-network:
    driver: bridge